/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Datos.HabitacionData;
import Entidades.habitacionSimple;

/**
 *
 * @author franc
 */
public class AgregarHabitacionesView extends javax.swing.JInternalFrame {

    HabitacionData habd = new HabitacionData();
    public AgregarHabitacionesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCanPer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCantCamas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTipoCamas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPrecioNoch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jEstado = new javax.swing.JRadioButton();
        jGuardar = new javax.swing.JButton();
        jModificar = new javax.swing.JButton();
        jEliminar = new javax.swing.JButton();
        jTipoHabitacion = new javax.swing.JComboBox<>();

        jLabel1.setText("Administracion Habitaciones");

        jLabel2.setText("Tipo de habitacion:");

        jLabel3.setText("Cantidad Max de Persona");

        jLabel4.setText("Cantidad de Camas:");

        jCantCamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCantCamasActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de Cama:");

        jTipoCamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoCamasActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio Noche");

        jLabel7.setText("Estado");

        jGuardar.setText("Guardar");
        jGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarActionPerformed(evt);
            }
        });

        jModificar.setText("Modificar");
        jModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarActionPerformed(evt);
            }
        });

        jEliminar.setText("Eliminar");

        jTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Doble", "Triple", "Suit" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPrecioNoch)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEstado))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jGuardar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jModificar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jEliminar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCanPer)
                                            .addComponent(jCantCamas)
                                            .addComponent(jTipoCamas, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(jTipoHabitacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCanPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCantCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTipoCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPrecioNoch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGuardar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jModificar)
                        .addComponent(jEliminar)))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCantCamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCantCamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCantCamasActionPerformed

    private void jTipoCamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoCamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTipoCamasActionPerformed

    private void jGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarActionPerformed
       
        String opcion = jTipoHabitacion.getSelectedItem().toString();
        
        switch (opcion){
        
            case "Simple": {
                
                habitacionSimple hs = new habitacionSimple(Integer.parseInt(jCantCamas.getText()), (double)Integer.parseInt(jCantCamas.getText()),
                        jTipoCamas.getText().toString(),jTipoHabitacion.getSelectedItem().toString(), Integer.parseInt(jCanPer.getText()), jEstado.isSelected());
            habd.CargarHab(hs);
            jTipoCamas.setText("");
            jCantCamas.setText("");
            jTipoCamas.setText("");
            jCanPer.setText("");
                break;
            
            }
            
            case "Doble": {
                
                habitacionSimple hs = new habitacionSimple(Integer.parseInt(jCantCamas.getText()), (double)Integer.parseInt(jCantCamas.getText()),
                        jTipoCamas.getText().toString(),jTipoHabitacion.getSelectedItem().toString(), Integer.parseInt(jCanPer.getText()), jEstado.isSelected());
            habd.CargarHab(hs);
             jTipoCamas.setText("");
            jCantCamas.setText("");
            jTipoCamas.setText("");
            jCanPer.setText("");
                break;
            
            }
            case "Triple": {
                
                habitacionSimple hs = new habitacionSimple(Integer.parseInt(jCantCamas.getText()), (double)Integer.parseInt(jCantCamas.getText()),
                        jTipoCamas.getText().toString(),jTipoHabitacion.getSelectedItem().toString(), Integer.parseInt(jCanPer.getText()), jEstado.isSelected());
            habd.CargarHab(hs);
             jTipoCamas.setText("");
            jCantCamas.setText("");
            jTipoCamas.setText("");
            jCanPer.setText("");
                break;
            
            }
            case "Suit": {
                
                habitacionSimple hs = new habitacionSimple(Integer.parseInt(jCantCamas.getText()), (double)Integer.parseInt(jCantCamas.getText()),
                        jTipoCamas.getText().toString(),jTipoHabitacion.getSelectedItem().toString(), Integer.parseInt(jCanPer.getText()), jEstado.isSelected());
            habd.CargarHab(hs);
             jTipoCamas.setText("");
            jCantCamas.setText("");
            jTipoCamas.setText("");
            jCanPer.setText("");
                break;
            
            }
        
        
        
        
        }
    }//GEN-LAST:event_jGuardarActionPerformed

    private void jModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jCanPer;
    private javax.swing.JTextField jCantCamas;
    private javax.swing.JButton jEliminar;
    private javax.swing.JRadioButton jEstado;
    private javax.swing.JButton jGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jModificar;
    private javax.swing.JTextField jPrecioNoch;
    private javax.swing.JTextField jTipoCamas;
    private javax.swing.JComboBox<String> jTipoHabitacion;
    // End of variables declaration//GEN-END:variables
}
